### ISSUE TITLE
CTD/Crash

### ISSUE THREAD

**Issue by RF-PT** [adwitkow/Bannerlord.EncyclopediaFilters#13]
Hey.

First congrats for the awesome mod/mods you have.

Second, i just got a CTD/crash, cant reload any of my saves and it onyl happened since i installed this mod, gonna leave the crash report.

https://report.butr.link/0029CD.html

Thanks in advance, best regards.

**Comment by adwitkow** [comment]
Hi, thanks for the report! I will look into it.

**Comment by adwitkow** [comment]
As we've agreed in the DMs, even though the crash occurs when a vanilla function is called by this mod, the root cause must lie within another module screwing with troop loadouts and such a crash could also occur during specific scenes without the involvement of EncyclopediaFilters.
